### ISSUE TITLE
DOH3 for CLI

### ISSUE THREAD

**Issue by janthony6** [nextdns/nextdns#812] opened 2023-03-04 00:10 UTC
I've enabled DOH3 for my mac's and iPhones by editing the config file. How do I enable DOH3 for CLI though? Where can this be edited or is it not a feature of CLI yet?

**Comment by GY8VSdYYzvL8-K6T** [comment] 2023-03-04 01:45
You mean you edited the MobileConfig file and uploaded it to your Apple devices? How did you change MobileConfig file to have accept DoH3?

**Comment by janthony6** [comment] 2023-03-04 01:47
> You mean you edited the MobileConfig file and uploaded it to your Apple devices? How did you change MobileConfig file to have accept DoH3?

download it from apple.nextdns.io. uncheck "sign configuration profile." open the file on your desktop in textedit. search for where it says apple.dns.nextdns.io....  change apple to doh3

it should say doh3.dns.nextdns.io.... save and then send it to your phone. do that process for each device. on your phone, go to settings, safari, advanced, experimental features and turn on http/3

**Comment by jimmystewpot** [comment] 2023-03-27 23:33
Something to note, http/3 is not yet part of the standard library in Go. While that does not mean the developers will not use third party libraries it's just worth noting.
See https://github.com/golang/go/issues/32204

**Comment by jimmystewpot** [comment] 2023-03-27 23:46
This is actually a duplicate of #658

**Closed** 2023-09-10 00:59 UTC
Labels: ✨ feature-request
