### ISSUE TITLE
NextDNS not working with ios 15

### ISSUE THREAD

**Issue by Zayatoshi** [nextdns/nextdns#518] opened 2021-06-09 21:45 UTC
Hello. I use NextDNS in pro version on all devices including iOS and it’s really fantastic. many thanks to the developer. however I upgraded to iOS 15 beta 1, and my NextDNS profile is no longer taken into account. it is marked unknown in the settings. when I go to the NextDNS page it says that this device is not using NextDNS. the ads are coming back, nothing is filtered and it is not the NextDNS dns that are used, but that of my principal. is it possible please to update to make compatibility with iOS 15 possible? thank you in advance. is looks.

**Context**
 - Version [e.g. 1.5.2]: 
 - Platform [e.g. macOS, ASUS-Merlin]:

**Comment by rs** [comment] 2021-06-09 21:57
Make sure you disable the Privacy Relay feature as it is currently conflicting with encrypted DNS. We reported this bug to Apple. This should be fixed in a future beta.

**Closed** 2021-06-09 23:34 UTC
Labels: 🐞 bug

**Comment by Zayatoshi** [comment] 2021-06-10 06:37
It has been done. The problem is the same. The nextdns.io profile no longer seems to work with IOS 15. When I log in with nextdns.io and the profile it says my phone is not using nextdns. While it is. It worked perfectly with IOS 14, and more with IOS 15. The problem is similar with the latest version of MAcos. It seems that Nextdns profiles / settings are no longer accepted by IOS 15 and Macos. a signature problem or something else seems to be. Would you please have a solution? thank you in advance.

**Comment by ThePowerOfDreams** [comment] 2021-06-10 07:11
Don't use a beta operating system if you expect everything to work correctly; the issue is with the OS and not NextDNS.

**Comment by Zayatoshi** [comment] 2021-06-10 07:13
Thank you for your answer. But has anyone seen similar issues with IOS 15?

**Comment by ThePowerOfDreams** [comment] 2021-06-10 07:34
This is not a discussion forum; go to Reddit.

**Comment by alex99r** [comment] 2021-06-13 00:30
works perfectly in IOS 15 with encrypted DNS. But displays "unknown" as a subname but is not a problem at all.
