### ISSUE TITLE
NextDNS hogging CPU resources on Edgerouter Lite and stops resolving domains

### ISSUE THREAD

**Issue by Tuinslak** [nextdns/nextdns#597] opened 2021-10-24 14:41 UTC
Since 2-3 days, for no particular reason, NextDNS is hogging ~100-150% cpu on my Edgerouter Lite (MIPS). 

<img width="1116" alt="Screen Shot 2021-10-24 at 22 37 19" src="https://user-images.githubusercontent.com/306680/138598959-166d3fc6-7534-4f5e-a7d8-ecebe501fef8.png">

Logs showing `doh resolve: context deadline exceeded`:

```
Oct 24 22:39:32 sg-erl nextdns[19837]: Query 10.3.34.38 TCP AAAA lh3.googleusercontent.com. (qry=54/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Oct 24 22:39:32 sg-erl nextdns[19837]: Query 10.3.34.38 TCP A lh3.googleusercontent.com. (qry=54/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Oct 24 22:39:33 sg-erl nextdns[19837]: Query 10.3.34.38 TCP AAAA lh3.googleusercontent.com. (qry=54/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Oct 24 22:39:33 sg-erl nextdns[19837]: Query 10.3.34.38 TCP A lh3.googleusercontent.com. (qry=54/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Oct 24 22:39:33 sg-erl nextdns[19837]: Query 10.3.34.38 TCP AAAA lh3.googleusercontent.com. (qry=54/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Oct 24 22:39:33 sg-erl nextdns[19837]: Query 10.3.34.38 TCP A lh3.googleusercontent.com. (qry=54/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Oct 24 22:39:33 sg-erl nextdns[19837]: Query 10.3.34.38 TCP AAAA lh3.googleusercontent.com. (qry=54/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Oct 24 22:39:34 sg-erl nextdns[19837]: Query 10.3.34.38 TCP A lh3.googleusercontent.com. (qry=54/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Oct 24 22:39:34 sg-erl nextdns[19837]: Query 10.3.34.38 TCP AAAA clients1.google.com. (qry=48/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Oct 24 22:39:35 sg-erl nextdns[19837]: Query 10.3.34.38 TCP A clients1.google.com. (qry=48/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
Oct 24 22:39:37 sg-erl nextdns[19837]: Query 10.3.34.38 TCP A clients1.google.com. (qry=48/res=12) cache fallback HTTP/2.0: doh resolve: context deadline exceeded
```

Weird errors restarting:

```
yeri@sg-erl:~$ sudo nextdns restart
Error: /config/scripts/post-config.d/nextdns.sh restart: exit status 1:
yeri@sg-erl:~$ sudo nextdns status
stopped
yeri@sg-erl:~$ sudo nextdns start
yeri@sg-erl:~$ sudo nextdns status
running
```

CPU is then back to ~normal (10-20%).

This is happening every few hours and all clients on the network stop resolving. 

```
yeri@sg-erl:~$ nextdns version
nextdns version 1.37.3
```

**Comment by jzelinskie** [comment] 2021-11-04 02:57
Pretty sure this is a duplicate of #586

**Comment by vincentbernat** [comment] 2021-11-25 21:01
Could you try with the snapshot in #618? It switches back to Go 1.16 instead of Go 1.17 which was one of the main change between 1.35 and 1.36. Comment back in #618 if it works or not. Thanks!

**Comment by Tuinslak** [comment] 2021-11-26 03:50
Okay, will let it run for a few days:

```
yeri@sg-erl:~$ NEXTDNS_VERSION=pr-618/SNAPSHOT-9483d8b sh -c 'sudo sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: edgeos
INFO: GOARCH: mips64_softfloat
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /config/nextdns/nextdns
INFO: INSTALL_RELEASE: 1.37.4
u) Upgrade NextDNS from 1.35.0 to 1.37.4
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
NextDNS installed and started using edgeos init
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c): e
yeri@sg-erl:~$ sudo nextdns version
nextdns version 1.37.4
```

**Comment by andrew-susanto** [comment] 2021-11-26 07:01
@Tuinslak I'm also observing this PR version, I think you still using the official 1.37.4 version. I'm running this PR version and haven't seen any problem in the past 6 hours. 

`ubnt@ubnt:~$ NEXTDNS_VERSION=pr-618/SNAPSHOT-9483d8b sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: edgeos
INFO: GOARCH: mipsle_softfloat
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /config/nextdns/nextdns
INFO: INSTALL_RELEASE: pr-618/SNAPSHOT-9483d8b
c) Configure NextDNS
r) Remove NextDNS
e) Exit`

`ubnt@ubnt:~$ nextdns version
nextdns version 0.0.0-SNAPSHOT-9483d8b`

Notice in INFO: INSTALL RELEASE it shows pr-618/SNAPSHOT-9483d8b and not 1.37.4 also in nextdns version it shows SNAPSHOT version.

**Comment by Tuinslak** [comment] 2021-11-26 07:04
Hmmm, okay, odd. Seems like my upgrade command just upgraded to the last version (I added `sudo` which likely caused the problem. Vaguely remember that a while back I needed sudo or else it would throw an error -- that doesn't seem to be the case anymore now)..

```
yeri@sg-erl:~$ NEXTDNS_VERSION=pr-618/SNAPSHOT-9483d8b sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: edgeos
INFO: GOARCH: mips64_softfloat
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /config/nextdns/nextdns
INFO: INSTALL_RELEASE: pr-618/SNAPSHOT-9483d8b
u) Upgrade NextDNS from 1.37.4 to pr-618/SNAPSHOT-9483d8b
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
NextDNS installed and started using edgeos init
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c): e
yeri@sg-erl:~$ nextdns version
nextdns version 0.0.0-SNAPSHOT-9483d8b
```

Thanks

**Comment by vincentbernat** [comment] 2021-11-26 07:23
Yes, by default `sudo` cleanup the environment, so you don't get the `NEXTDNS_VERSION` variable.

**Closed** 2023-09-10 00:53 UTC
