### ISSUE TITLE
UDM Pro IPv6 setup only enables first LAN interface

### ISSUE THREAD

**Issue by elarsson1** [nextdns/nextdns#747] opened 2022-10-15 00:17 UTC
**Context**
 - CLI Version: 1.37.11
 - Platform: ubios

&lt;Describe the bug>

The fix for #422 appears to only bind NextDNS CLI to the first LAN interface on the system and only sets up ip6tables to redirect port 53 to nextdns on port 5555 on the first LAN interface IPv6 GUA. Other networks defined on the controller IPv6 DNS continues to be answered by dnsmasq. 

On my Ubiquity setup I have a LAN network (used only for Unifi devices), Comp, IoT, and Guest networks. UDM's DHCP6 and RA server hands out the IPv6 DNS address to match the UDM's interface IP in that subnet. From the LAN subnet, DNS queries to the UDM's router address are intercepted by iptables and routed to NextDNS. On the other networks, queries to the UDM's address in that subnet are answered by dnsmasq and not sent to the NextDNS daemon. Further, the way iptables are being set up, DNS requests to the LAN interface IPv6 address from other subnets are dropped, so changing DHCP6 and RA configuration to hand out the LAN interface address instead of the subnet's UDM interface address is not an option as a workaround. 

IPv4 does not have this issue. NextDNS binds to all interfaces in the system and iptables are configured to redirect 53 to 5555 on all interfaces.

**Comment by dlrudie** [comment] 2022-12-01 20:00
May be a duplicate of #711 as well. I have the same issue so every time I restart my UDMP I connect via SSH and run the ip6tables commands to make it operate as expected.

**Comment by jimmystewpot** [comment] 2023-03-24 04:54
#819 has been created as the previous pull request #799 was rolled back

**Comment by 2mcdev** [comment] 2023-08-05 13:18
Hi, First off, thank you for the work on this issue! I currently keep ipv6 disabled on my UDMP because of this. Is there any reason that is keeping this PR from being merged?

**Comment by jimmystewpot** [comment] 2023-08-10 04:15
I can't comment on why the PR is taking so long.

A work around is to manually set the DNS servers for IPv6 to the nextdns IPv6 provided DNS services associated with your profile.

**Closed** 2023-09-11 00:14 UTC
Labels: 🐞 bug
