### ISSUE TITLE
2 hops client problem

### ISSUE THREAD

**Issue by crssi** [nextdns/nextdns#513] opened 2021-06-05 08:25 UTC
@rs Not sure how to name it but here you go.
I don't know if worth to mention, but this info might give you some insight.

One of "my" setups.
1. [Latest OpenWRT, that is version 19.07.7](https://openwrt.org/toh/mikrotik/rb2011uias) on Mikrotik RouterBoard RB2011-UiAS-2HnD-IN
2. Old NextDNS, that is version 1.10.1-2 (luci-app-nextdns, git-21.056.55117-aadfafa-1)

This was working great until a few days ago.

But just before this move https://github.com/nextdns/nextdns/issues/500#issuecomment-855153166 there was a strange behavior that I have noticed on iPhone 8+ which is up-to-date, that is version 14.5.1, and latest NextDNS client.

On a router NextDNS cli other NextDNS profile is in use than on iPhone NextDNS client.

If I use iPhone with **enabled** NextDNS client out of this network (any other network that is) then iPhone doesn't suffer any problems.
If I have used iPhone with **disabled** NextDNS client on this network it was also OK.

But when I have used iPhone on this network and with NextDNS client **enabled** than DNS failed to resolve.
As said, this behaviour was before https://github.com/nextdns/nextdns/issues/500#issuecomment-855153166, now it is again working OK.

I don't use `Block Bypass Methods` on any of my NextDNS profiles.

If you have any questions or need for additional info or action from my side, then I am at your disposal, just let me know.

Cheers

**Comment by rs** [comment] 2021-06-05 11:07
With nextdns off on the iphone but on your network, what do you get for https://ping.nextdns.io?

**Comment by crssi** [comment] 2021-06-05 13:19
As said, today there are no problems. Also I was eager to update the OpenWRT NextDNS cli which is now at 1.32.1-2, git-21.132.36199. I hope I haven't spoiled the soup for you 😢 

Anyway, the requested results are:

1st run
```
■ anexia-vie       13 ms  (anycast2, ultralow1)
  exoscale-vie     15 ms  (ultralow2)
  anexia-prg       19 ms
  anexia-zrh       26 ms
  vultr-fra        27 ms
  zepto-fra        29 ms
  zepto-mil        29 ms  (anycast1)
  serverwala-mil   30 ms
  exoscale-zrh     35 ms
  zepto-prg        35 ms
```

2nd run after reconnecting:
```
  exoscale-vie     19 ms  (ultralow2)
■ anexia-vie       20 ms  (anycast2, ultralow1)
  vultr-fra        24 ms
  anexia-prg       27 ms
  anexia-zrh       28 ms
  zepto-fra        28 ms
  zepto-mil        31 ms  (anycast1)
  zepto-prg        33 ms
  exoscale-zrh     42 ms
  serverwala-mil  185 ms
```

**Comment by rs** [comment] 2021-06-05 13:45
It was probably a bug in the cli that has been fixed. Hard to say. Let’s close if the problem is fixed now.

**Closed by rs** 2021-06-05 13:45 UTC
Labels: 🐞 bug

**Comment by crssi** [comment] 2021-06-05 16:38
Sure... thank you for fast response.

Wish you best and cheers
