### ISSUE TITLE
OSX El capitan

### ISSUE THREAD

**Issue by cocoflan** [nextdns/nextdns#471] opened 2021-04-22 19:36 UTC
Unhandled case where "resolver" is not present. when trying to run nextdns tool and browser.

**Comment by rs** [comment] 2021-04-22 21:46
Please provide more context on how to reproduce the issue and on what the issue is exactly (expected vs reality).

**Comment by cocoflan** [comment] 2021-04-22 22:24
Ok it is on a system of a friend, wil ask him to send me some more info soon.

Greetings

**Comment by rs** [comment] 2021-04-22 22:33
Closing for now, please reopen when you have more context.

**Closed by rs** 2021-04-22 22:33 UTC
Labels: 🐞 bug
