### ISSUE TITLE
DNS requests over plain http port 80

### ISSUE THREAD

**Issue by olbrew** [nextdns/nextdns#95] opened 2020-02-25 01:32 UTC
Since enabling NextDNS as my primary DNS provider I've seen much more requests than usual over port 80 to IPv4 addresses.
I've manually checked some of these requests and looked up a domain name for them and they all point to subdomains from big CDNs. 
Some examples are akamaitechnologies.com, 1e100.net (Google) and cloudfront.net (AWS).
With other DNS providers these requests don't happen.

**Comment by olbrew** [comment] 2020-02-25 01:32
I'm a really big fan of the work you're doing with NextDNS and would like to contribute in any way possible to get this issue resolved.

**Comment by rs** [comment] 2020-03-13 02:46
Which client are you using?

**Comment by olbrew** [comment] 2020-03-17 02:28
Hi @rs, I am using the official VPN client but also followed the settings on the NextDNS website for setting up my OS and browser so that if one would fail the other would back it up. A defense in depth so to speak. 
Your comment made me disable each one to see which one was the culprit and it appears to be my browser settings. I use Firefox as a browser and when undoing the Firefox specific instructions on my.nextdns.io I stop seeing connections over port 80 while browsing.
With the VPN still active visiting NextDNS through Firefox still gives me the green light: This device is using NextDNS with this configuration, indicating that it should still be using NextDNS servers for name resolution.

**Comment by rs** [comment] 2020-03-17 07:43
Thx for the clarification. As it is not a client under our control, I’m going to close this issue. Please reopen if you think otherwise.

**Closed by rs** 2020-03-17 07:43 UTC

**Comment by olbrew** [comment] 2020-03-17 17:34
Ok, but I think almost all people using Firefox will encounter this issue when setting up NextDNS through it and since it was added to the approved list of trusted recursive resolvers it should work properly. I'll log an issue on Bugzilla then.

**Comment by olbrew** [comment] 2020-03-20 01:01
Over the last few days I've noticed that the issue actually also occurs, though less frequently without any Firefox specific settings enabled and only using the VPN client.
The fact that it occurrs less frequently might be due to the the `trr.mode` setting set to `3` forcing Firefox to only use the native resolver without a fallback. 
Though I would assume that the VPN client would also force all DNS requests over NextDNS network without using a fallback.

In any case I would reopen this issue because it exhibits the behavior with the VPN client as well, regardless of browser specific config.

**Comment by rs** [comment] 2020-03-20 01:04
We or firefox will never send DNS queries over port 80. Do you have a pcap showing what you are seeing?

**Comment by olbrew** [comment] 2020-03-20 01:07
Also rather curiously searching for the DNS name with the `host` command in the Terminal does return a proper DNS name when using the NextDNS service through port 53.
It still seems to happen exclusively for internal networks and CDNs like 1e100.net

**Comment by rs** [comment] 2020-03-20 01:10
Please provide examples.

**Comment by olbrew** [comment] 2020-03-20 01:12
> We or firefox will never send DNS queries over port 80. Do you have a pcap showing what you are seeing?

No PCAP yet, but I use the Little Snitch application firewall. I've set it to catch Firefox's connection requests over port 80. Since most of the websites I visit nowadays are on https it doesn't trigger often anymore. But since installing and setting up NextDNS I noticed a sharp uptick.

Just now Little Snitch asked me permission for this request:

On 20 Mar 2020, Firefox Developer Edition tried to establish a connection to 172.217.16.195 on TCP port 80 (http). The request was allowed via connection alert.

Running `172.217.16.195` through host gives me:
`195.16.217.172.in-addr.arpa` domain name pointer fra16s08-in-f195.1e100.net.`
`195.16.217.172.in-addr.arpa domain name pointer fra16s08-in-f3.1e100.net.`

**Comment by rs** [comment] 2020-03-20 01:56
The title of the issue is misleading. Those are not DNS queries over plain HTTP, but just HTTP requests. While it's in the clear, you could dump the content of the request so you can understand better what it is about.

You can try to run NextDNS with no blocklist. Perhaps trackers are trying different URLs/protocol because primary hostnames are blocked for instance.
