### ISSUE TITLE
Issues on Ubuntu 16/18

### ISSUE THREAD

**Issue by therealsamsquanch** [nextdns/nextdns#106] opened 2020-03-19 01:03 UTC
I was running Ubuntu 16 and later I upgraded to Ubuntu 18. NextDNS always failed to start after installing it for the first time or after a reinstall, on both Ubuntu versions. First it says that something else is already using port 53 (in my case it was systemd-resolved). If I stop the service using the port 53 and restart nextdns, nslookup says:
`
 reply from unexpected source: 127.0.0.1#53, expected 127.0.0.53#53
`

 To fix all these issues, this is what I do:

`sudo service systemd-resolved stop`
`sudo systemctl disable systemd-resolved.service`
`sudo rm /etc/resolv.conf`
`sudo service nextdns restart`

Then it works as intended, I can restart the system and nextdns will run just fine the next time. Just posting it here in case someone else has this issue.

**Comment by rs** [comment] 2020-03-19 01:53
What version do you have? Do you have setup-router on?

**Comment by therealsamsquanch** [comment] 2020-03-25 20:38
Sorry for the late reply. I can confirm that I had these issues at least on v1.4.33 and v1.4.35. Can't say about v1.4.34 because I uninstalled v1.4.33 and went for v1.4.35. Yes, I do have setup-router enabled.

**Comment by wii747** [comment] 2020-05-03 13:50
I had the same issue on a fresh install of Ubuntu 20.04 with the latest cli install. system-resolved was active so I done the steps listed by therealsamsquanch and it is now working.

**Comment by rs** [comment] 2020-05-04 05:32
I can't reproduce with 19. @wii747 can you please show what you get for `nextdns config` (redacting your config id).

**Comment by wii747** [comment] 2020-05-04 07:52
Hi

I have just performed an fresh install of ubuntu 20.04 and same error

login as: wii747
wii747@192.168.1.79's password:
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-28-generic x86_64)
wii747@dns02:~$ sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: ubuntu
INFO: GOARCH: amd64
INFO: GOOS: linux
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
[sudo] password for wii747:
OK
Hit:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://gb.archive.ubuntu.com/ubuntu focal-updates InRelease [106 kB]
Get:4 http://gb.archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
Get:5 http://gb.archive.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Ign:3 https://dl.bintray.com/nextdns/deb stable InRelease
Get:6 https://dl.bintray.com/nextdns/deb stable Release [9,511 B]
Get:7 https://dl.bintray.com/nextdns/deb stable Release.gpg [821 B]
Get:8 https://dl.bintray.com/nextdns/deb stable/main amd64 Packages [5,279 B]
Fetched 327 kB in 1s (621 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  nextdns
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 3,178 kB of archives.
After this operation, 7,967 kB of additional disk space will be used.
Get:1 https://dl.bintray.com/nextdns/deb stable/main amd64 nextdns amd64 1.5.4 [                                                                                                                                                             3,178 kB]
Fetched 3,178 kB in 0s (9,617 kB/s)
Selecting previously unselected package nextdns.
(Reading database ... 70776 files and directories currently installed.)
Preparing to unpack .../nextdns_1.5.4_amd64.deb ...
Unpacking nextdns (1.5.4) ...
Setting up nextdns (1.5.4) ...
NextDNS installed and started using systemd init
NextDNS Configuration ID:
Invalid configuration ID.sh: 476: shift: can't shift that many
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: y
Only use DNS servers located in jurisdictions with strong privacy laws.
This may increase latency.
Enable hardened privacy mode (may increase latency)? [y|N]: n
Accept DNS request from other LAN hosts.
Setup as a router? (y/n): y
Changes DNS settings of the host automatically when nextdns is started.
If you say no here, you will have to manually configure DNS to 127.0.0.1.
Automatically configure host DNS on daemon startup? [Y|n]: y
NextDNS installed and started using systemd init
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c): e
wii747@dns02:~$ sudo su
root@dns02:/home/wii747# nextdns status
not installed
root@dns02:/home/wii747# nextdns log
              -- Logs begin at Mon 2020-05-04 07:19:55 UTC, end at Mon 2020-05-04 07:49:27 UTC. --
May 04 07:44:22 dns02 systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 04 07:44:22 dns02 nextdns[2939]: Starting NextDNS 1.5.4/linux on localhost:53
May 04 07:44:22 dns02 nextdns[2939]: Listening on TCP/127.0.0.1:53
May 04 07:44:22 dns02 nextdns[2939]: Listening on UDP/127.0.0.1:53
May 04 07:44:40 dns02 nextdns[2939]: Received signal: terminated
May 04 07:44:40 dns02 systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
May 04 07:44:40 dns02 nextdns[2939]: Stopping NextDNS 1.5.4/linux
May 04 07:44:40 dns02 nextdns[2939]: NextDNS 1.5.4/linux stopped
May 04 07:44:40 dns02 systemd[1]: nextdns.service: Succeeded.
May 04 07:44:40 dns02 systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
May 04 07:44:40 dns02 systemd[1]: Started NextDNS DNS53 to DoH proxy..
May 04 07:44:40 dns02 nextdns[3159]: Starting NextDNS 1.5.4/linux on :53
May 04 07:44:40 dns02 nextdns[3159]: Listening on TCP/:53
May 04 07:44:40 dns02 nextdns[3159]: Starting discovery resolver
May 04 07:44:40 dns02 nextdns[3159]: Listening on UDP/:53
May 04 07:44:40 dns02 nextdns[3159]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
May 04 07:44:40 dns02 nextdns[3159]: Error: proxy: tcp: listen tcp :53: bind: address already in use
May 04 07:44:40 dns02 systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
May 04 07:44:40 dns02 systemd[1]: nextdns.service: Failed with result 'exit-code'.
                                                                                                                                           '.
root@dns02:/home/wii747#

**Comment by rs** [comment] 2020-05-04 07:55
Are you intending to use this host as a router?

**Comment by wii747** [comment] 2020-05-04 08:01
@rs yes I am intending to use this host as a router

**Comment by dogsbody** [comment] 2021-02-14 22:15
Alternative install option that I am using and is working well...
```
sudo sed -i -r 's/^#?DNSStubListener=.*/DNSStubListener=no/' /etc/systemd/resolved.conf
sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
sudo systemctl restart systemd-resolved.service
sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
```

**Closed** 2021-03-28 21:45 UTC
Labels: 🐞 bug, 🖥️ ubuntu, 🧩 router-setup
