### ISSUE TITLE
Unifi Dream Machine Pro Isolated Networks lose resolution  

### ISSUE THREAD

**Issue by johnybradshaw** [nextdns/nextdns#562] opened 2021-08-15 15:59 UTC
I have a Unifi Dream Machine Pro which I’ve installed the CLI on to. For my IoT network, which I run with Device Isolation enabled, nothing on that network will resolve DNS until I disable Device Isolation. 

I’ve tried adding local and remote dns IPs to the allow list but it does not help fix it.

**Comment by linuxfrag** [comment] 2021-08-18 22:42
Its been a while but I believe you need to set a firewall rule to allow dns to nextdns cli. Same as with guest networks which are isolated. So create a rule like the following:

Type			Guest Local
Description		allow NextDNS
Rule Applied		Before Predefined Rules
Action			Accept
IPv4 Protocol		TCP/UDP
Source			Any
Destination		Address/Port Group
IPv4 Address Group	Any
Port Group		NextDNS[5553]

**Comment by johnybradshaw** [comment] 2021-08-19 13:17
Perfect! Thanks that sorted it

**Comment by BirdInFire** [comment] 2021-09-07 16:28
@rs Can this issue be added in wiki (troubleshot) and closed after ?

**Comment by rs** [comment] 2021-09-07 17:12
It's better if the rule is added dynamically by the CLI.

**Comment by jfroy** [comment] 2022-06-30 01:30
This is a duplicate of #457.

**Comment by BirdInFire** [comment] 2022-06-30 02:03
> This is a duplicate of #457.

maybe but not @johnybradshaw fault the other title is not explicit on witch hardware had a problem
Not everyone will read all hunded of issue open to be sure there is no duplicate we do search by keyword

**Comment by jfroy** [comment] 2022-06-30 02:13
> > This is a duplicate of #457.
> 
> 
> 
> Edit on UDM isolated network != guest

I think the fix is largely going to be the same? I was only trying to stitch the issues together.

**Comment by BirdInFire** [comment] 2022-06-30 02:16
> > > This is a duplicate of #457.
> > 
> > 
> > Edit on UDM isolated network != guest
> 
> I think the fix is largely going to be the same? I was only trying to stitch the issues together.

it's possible but i doubt, since guest is by default (and not possible to disable) isolated, where isolated network must be manually defined, so even if the problem is the same i think the fix (in cli way) must be different (but i can be wrong).

**Comment by jfroy** [comment] 2022-06-30 16:17
> > > > This is a duplicate of #457.
> > > 
> > > 
> > > Edit on UDM isolated network != guest
> > 
> > 
> > I think the fix is largely going to be the same? I was only trying to stitch the issues together.
> 
> it's possible but i doubt, since guest is by default (and not possible to disable) isolated, where isolated network must be manually defined, so even if the problem is the same i think the fix (in cli way) must be different (but i can be wrong).

Network isolation is enforced by the Guest Hotspot profile, which you can in fact edit. If you wanted, you could allow a guest network to fully communicate with non-guest networks (more commonly you may allow communication to a jump box, specific hosts, or specific ports like ssh).

<img width="616" alt="Screenshot 2022-06-30 at 09 16 58" src="https://user-images.githubusercontent.com/49554/176727487-f8106891-2c25-42d3-b275-76a2264c569f.png">

Anyways, I can report that the instructions still work with Network 7.2.87.

**Comment by plmcgrn** [comment] 2023-01-25 06:00
Chiming in as I found this way late into troubleshooting.  I think the note on the firewall rule should at least be added to the Unifi wiki page, if it can't be automated as part of the CLI install.

**Closed** 2023-09-10 00:52 UTC
