### ISSUE TITLE
doh resolve: context deadline exceeded

### ISSUE THREAD

**Issue by jissou06** [nextdns/nextdns#417] opened 2021-02-07 13:26 UTC
Hi

Testing nextdns since yesterday 
I do enjoy this project

Yesterday I decide to install by the Debian Way (no usage of sudo)
----
wget -qO - https://nextdns.io/repo.gpg | apt-key add -
echo "deb https://nextdns.io/repo/deb stable main" | tee /etc/apt/sources.list.d/nextdns.list
apt install apt-transport-https 
apt update
apt install nextdns
-----

Everything worked fine
and I played with the interface 
https://my.nextdns.io/ID/setup

This morning, booting the computer 
have a look to the interface 
https://my.nextdns.io/ID/setup

But it seem I a'm not detected as connected

nextdns log tell me :
------
févr. 07 13:49:49 debian1 nextdns[627]: Connected 45.90.28.0:443 (con=22ms tls=320ms, TLS13)
févr. 07 13:49:49 debian1 nextdns[627]: Switching endpoint: https://dns1.nextdns.io#45.90.28.0,2a07:a8c0::
févr. 07 13:49:49 debian1 nextdns[627]: Query 127.0.0.1 UDP AAAA debian1. (qry=25/res=12) 5339ms : doh resolve: context deadline exceeded
-----

Restarting the service 
nextdns restart
works fine
The portal tells me 
"Perfect this computer use nextDNS with this config"
Amazing !

nextdns log tell me :
------
févr. 07 14:07:43 debian1 nextdns[627]: Received signal: terminated
févr. 07 14:07:43 debian1 systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
févr. 07 14:07:43 debian1 nextdns[627]: Stopping NextDNS 1.10.1/linux
févr. 07 14:07:43 debian1 nextdns[627]: Deactivating
févr. 07 14:07:43 debian1 nextdns[627]: NextDNS 1.10.1/linux stopped
févr. 07 14:07:43 debian1 systemd[1]: nextdns.service: Succeeded.
févr. 07 14:07:43 debian1 systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
févr. 07 14:07:43 debian1 systemd[1]: Started NextDNS DNS53 to DoH proxy..
févr. 07 14:07:43 debian1 nextdns[2635]: Starting NextDNS 1.10.1/linux on localhost:53
févr. 07 14:07:43 debian1 nextdns[2635]: Listening on TCP/[::1]:53
févr. 07 14:07:43 debian1 nextdns[2635]: Listening on UDP/127.0.0.1:53
févr. 07 14:07:43 debian1 nextdns[2635]: Listening on TCP/127.0.0.1:53
févr. 07 14:07:43 debian1 nextdns[2635]: Listening on UDP/[::1]:53
févr. 07 14:07:47 debian1 nextdns[2635]: Connected 45.90.28.0:443 (con=27ms tls=101ms, TLS13)
févr. 07 14:07:48 debian1 nextdns[2635]: Connected 37.252.225.79:443 (con=28ms tls=187ms, TLS13)
févr. 07 14:07:48 debian1 nextdns[2635]: Switching endpoint: https://dns.nextdns.io.#37.252.225.79,2a00:11c0:2:998::3,193.168.204.73,2a0e:9900:0:1::1:2
févr. 07 14:07:48 debian1 nextdns[2635]: Activating
--------------

Rebooting the computer give me same behavior 

**Context**
 - Version:  nextdns version 1.10.1
 - Platform : Debian Testing/sid

**Comment by davidmehren** [comment] 2021-02-17 11:13
I can reliably trigger this behavior by activating a VPN connection (split-tunneling, OpenVPN).  
Nextdns logs `Network change detected: tap0 added`, but then stopps resolving all querys with errors like `Query 127.0.0.1 UDP A detectportal.firefox.com. (qry=42/res=12) cached HTTP/2.0: doh resolve: context deadline exceeded`.  
Only after about two minutes something seems to time out, nextdns reports `Connected 199.247.16.158:443 (con=10ms tls=16ms, TLS13)` and resolving works again.

I'm currently working around this issue by manually restarting `nextdns.service` every time I connect to a VPN, but as you can imagine this is quite tedious.

**Comment by syscll** [comment] 2021-03-11 04:31
Have also been experiencing this bug for the last few version. Seems to happen after every wake from suspend/hibernate.

Logs are filled with these until I manually restart the nextdns service:
```
Mar 10 20:18:29 t14 nextdns[942]: Query 127.0.0.1 UDP A example.org. (qry=29/res=12) 5000ms : doh resolve: context deadline exceeded
```

**Context**
- Version: nextdns version 1.11.0
- Platform: Linux 5.11.4-arch1-1 x86_64

**Comment by ser** [comment] 2021-08-19 18:46
in my point of view these errors are related to the length of the answer. i'm getting it frequently from spamassasin filters related queries
```
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A pacifica.edu.multi.surbl.org. (qry=57/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A michigan.gov.dob.sibl.support-intelligence.net. (qry=75/res=12) 5001ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A pacifica.edu.dob.sibl.support-intelligence.net. (qry=75/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A charitynavigator.org.multi.surbl.org. (qry=65/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A charitynavigator.org.dob.sibl.support-intelligence.net. (qry=83/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A psychedelicscience.org.dob.sibl.support-intelligence.net. (qry=85/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A list-manage.com.multi.surbl.org. (qry=60/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A list-manage.com.dob.sibl.support-intelligence.net. (qry=78/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A freewill.com.dob.sibl.support-intelligence.net. (qry=75/res=12) 5001ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A reddit.com.dob.sibl.support-intelligence.net. (qry=73/res=12) 5001ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A zoom.us.dob.sibl.support-intelligence.net. (qry=70/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A mdmaptsd.org.dob.sibl.support-intelligence.net. (qry=75/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A entheogeneration.community.dob.sibl.support-intelligence.net. (qry=89/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A tellurideinstitute.org.dob.sibl.support-intelligence.net. (qry=85/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A tellurideinstitute.org.multi.surbl.org. (qry=67/res=12) 5001ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A clinicaltrials.gov.multi.surbl.org. (qry=63/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A centerforpsychedelicmedicine.org.dob.sibl.support-intelligence.net. (qry=95/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A clinicaltrials.gov.dob.sibl.support-intelligence.net. (qry=81/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A insight-conference.eu.dob.sibl.support-intelligence.net. (qry=84/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A psychedeliccoalitionforhealth.com.dob.sibl.support-intelligence.net. (qry=96/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A maps.org.dob.sibl.support-intelligence.net. (qry=71/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A fluencetraining.com.multi.surbl.org. (qry=64/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A sageinst.org.multi.surbl.org. (qry=57/res=12) 5001ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A sageinst.org.dob.sibl.support-intelligence.net. (qry=75/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A fluencetraining.com.dob.sibl.support-intelligence.net. (qry=82/res=12) 5000ms : doh resolve: context deadline exceeded
Aug 19 18:18:42 relief2 nextdns[63271]: Query 10.77.1.12 UDP A congress.gov.dob.sibl.support-intelligence.net. (qry=75/res=12) 5001ms : doh resolve: context deadline exceeded

```

**Comment by Yinchie** [comment] 2021-12-16 21:58
Same issue here on Manjaro Linux.
Running a VPN + NextDNS.
To fix it, manually restart NextDNS.

**Comment by caleb-allen** [comment] 2022-03-13 00:14
I have the same setup as @Yinchie, although without any active VPN configurations.

 I ran `nextdns restart` and waited for 15+ seconds before it produced an error.

 I restarted my machine, and after a few minutes of functioning perfectly had about 1 minute of DNS timeouts. Since then I haven't seen the issue, but I don't know the cause.

**Closed** 2023-09-10 00:48 UTC
Labels: 🐞 bug
